language: cpp
sudo: enabled
dist: precise
install: "./install-dependencies.sh"
script: "./build.sh"
git:
  depth: 1
  submodules: false
before_deploy:
- git config --local user.name "ice0"
- git config --local user.email "konoplin@gmail.com"
- git tag -f "latest"
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: Le/8VEkuKN306IK3QqIcgfSdFESBHGoFJ5975T1zxXCnDYCd3J2VfH0HBFFAW0g1d+hglkK/vJLue/HX1yLinNSPWytXmlAsi02vKRhpPjFU854qJN2V0ixqe4ogdwP/No81diliUWm6F9VD2Qv/SCvBJVcjqjVn7rNDO5kx+wgGuYvKvPvJ3RJ+D4ZpcJdCGvISgBaN+sa7YpbrgefWqiNCcXGYJTD0fGFpCNyxT7b80PcmLC9E1bWVlZpaZyJtGUhNSGQb84uP3IDvyQW8H2q1xGgtEMhQl7WhCwG/d9+QkX1zzOYqEkkXB3zz8MimR5xECGDZWLgahc88AtIBmwa6kNuX7jzS6bPm3/cYzEsYZeXG0d8FbvDD4gr8P3K2UZfoDluW9XCwnXfkxP5xvJN3nOyJSIHZp3a5BFePgSQo2ruteKG7ra/M3CZ+3qYyT7HLe5KOcCmnIyqA1y1vx6ILy6gFzCP5mDozd+hMltuOHLoKs5kPXi2YuiBVLoNcTusjbA9sEDeNnyjPEC9iyv8fMCajj7DBiDZoHwgFgUXykut0PTCLxzYPR8G99mZBWSxe0I7tj4BHxJqZvlHkou5/0Gcr84ujGki6I/BogUswF7nRzazTFkFeo1PmYCIgnygoBCsq/ypbV9pf/C9R4FwZATORrT13U6yIfi1pi90=
  file: build.tgz
  on:
    repo: ice0/mpm
