language: cpp
sudo: enabled
dist: precise
install: "./install-dependencies.sh"
script: "./build.sh"
before_deploy:
- git config --local user.name "ice0"
- git config --local user.email "konoplin@gmail.com"
#- git tag "latest"
deploy:
  provider: releases
  api_key:
    secure: GVGGBHb1vujiOQ9FSkJlJ6OdaBTdGFnZ3r/ZSmvqFYlMSfYdc1gK3P02L3efTBNP0b9lnRTZvcAElzJY0IqrqlvRr6ke6PMLLgDM6p1GCK7TGyQ1cEvkdZR0JxVyv/y69Ta1pRw8ueMkRMh6V1inKCFgFkQF6lTSaXqvCQBX2nA+TpaMuMi1uNiPK9eRmj5cF8kb45mIi1/160zHrgs1PQmvruEcoA+fF2jZdh6E0gb8OSB/jOOv2KybmnEk2j6QmWKAd0eJSj3xVyhYV1ySfgT4UXTfGTHn60cbcr8OY7mrT7rKLkEP6ZfG+fM32FDKJqt0mWnk5A6crHdVdbGA36KDQr4997Bw1QrCd6ZoxcS6e4F6OANIbjWhdpRODA+CKpVsqvx0BMqMfGiVqxlZ0J3MfWKF6mrI08Bee58holr1cHD1FAfsCDTP3Q3E5YcRa2LMpVJkzxp8XIesRghA1EzHT5sCM+c9WwsDK00JHN36CXZ6J7jVkEoQJzAX3H5lbGzm6JCzgCvepXcBSXiprRWApHs2DUs80HZNR/Te7Hf4X9GjygO9SN61ywCtQGzdANayazSTWV37sgvILKl+oaiG06Wyh3QTYi3dnxvees93nUO53dPoXIx0e0lKKrgVAp1crclZ36ZUEeOngQftyCnWlVaCtv2Nuy+GDOJ7CP0=
  file: build.tgz
  skip_cleanup: true
  overwrite: true
env:
  global:
    secure: GVGGBHb1vujiOQ9FSkJlJ6OdaBTdGFnZ3r/ZSmvqFYlMSfYdc1gK3P02L3efTBNP0b9lnRTZvcAElzJY0IqrqlvRr6ke6PMLLgDM6p1GCK7TGyQ1cEvkdZR0JxVyv/y69Ta1pRw8ueMkRMh6V1inKCFgFkQF6lTSaXqvCQBX2nA+TpaMuMi1uNiPK9eRmj5cF8kb45mIi1/160zHrgs1PQmvruEcoA+fF2jZdh6E0gb8OSB/jOOv2KybmnEk2j6QmWKAd0eJSj3xVyhYV1ySfgT4UXTfGTHn60cbcr8OY7mrT7rKLkEP6ZfG+fM32FDKJqt0mWnk5A6crHdVdbGA36KDQr4997Bw1QrCd6ZoxcS6e4F6OANIbjWhdpRODA+CKpVsqvx0BMqMfGiVqxlZ0J3MfWKF6mrI08Bee58holr1cHD1FAfsCDTP3Q3E5YcRa2LMpVJkzxp8XIesRghA1EzHT5sCM+c9WwsDK00JHN36CXZ6J7jVkEoQJzAX3H5lbGzm6JCzgCvepXcBSXiprRWApHs2DUs80HZNR/Te7Hf4X9GjygO9SN61ywCtQGzdANayazSTWV37sgvILKl+oaiG06Wyh3QTYi3dnxvees93nUO53dPoXIx0e0lKKrgVAp1crclZ36ZUEeOngQftyCnWlVaCtv2Nuy+GDOJ7CP0=
