language: cpp
sudo: enabled
dist: precise
install: "./install-dependencies.sh"
script: "./build.sh"
git:
  depth: 1
  submodules: false
before_deploy:
- git config --local user.email "builds@travis-ci.com"
- git config --local user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
#- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
#- git fetch --tags
- git tag "latest" -fa -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q -f https://$GH_TOKEN@github.com/ice0/mpm --tags
#- git config --local user.name "ice0"
#- git config --local user.email "konoplin@gmail.com"
#- git tag -f "latest"
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  prerelease: true
  name: "night"
  api_key: $GH_TOKEN
  file: build.tgz
  on:
    repo: ice0/mpm
