# require the branch name to be master
#if: branch = master

# require the tag name to match a regular expression
#if: tag =~ ^v1
if: NOT (tag = latest AND type = push)

# require the event type to be either `push` or `pull_request`
#if: type IN (push, pull_request)

language: cpp
matrix:
  include:
    - os: linux
      sudo: enabled
      dist: precise
    - os: osx
env:
  - BUILD_FILENAME=build-$TRAVIS_OS_NAME.$TRAVIS_BUILD_NUMBER.tgz
install: "ci/travis/install-dependencies.sh"
script:  "ci/travis/build.sh"
git:
  depth: 1
  submodules: false
before_deploy: "ci/travis/push_latest_tag_if_needed.sh"
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  prerelease: true
  latest: true
  name: "latest"
  api_key: $GH_TOKEN
  file: $BUILD_FILENAME
  on:
    repo: ice0/mpm
