# require the branch name to be master
#if: branch = master

# require the tag name to match a regular expression
#if: tag =~ ^v1
if: NOT (tag = latest AND type = push)

# require the event type to be either `push` or `pull_request`
#if: type IN (push, pull_request)

language: cpp
matrix:
  include:
    - os: linux
      sudo: enabled
      dist: precise
    - os: osx

install: "./install-dependencies.sh"
script: "./build.sh"
git:
  depth: 1
  submodules: false
before_deploy:
- git config --local user.email "builds@travis-ci.com"
- git config --local user.name "Travis CI"
#- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
- git tag "latest" -fa -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q -f https://$GH_TOKEN@github.com/ice0/mpm --tags
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  prerelease: true
  latest: true
  name: "latest"
  api_key: $GH_TOKEN
  file: build-$TRAVIS_OS_NAME.tgz
  on:
    repo: ice0/mpm
